### ISSUE TITLE
Re: 'Accessibility Personas'

### ISSUE THREAD

**Issue by Julieuserresearch** [alphagov/accessibility-personas#82]
Problem with 'Accessibility Personas' (https://alphagov.github.io/accessibility-personas/) - Hi there this is a content problem - When we were looking at these personas one of my team questioned the use use of the term 'Aspergers' - I believe this is not the correct terminology any more.

**Comment by selfthinker** [comment]
This was fixed in #92. (It's not live yet, it will probably be published next week.)
